/**
 * FHIR Schema Validation Tests
 *
 * These tests validate that the data generated by dataGenerator.ts (Faker.js)
 * conforms to the official HL7 FHIR R4 JSON Schema.
 *
 * AJV (Another JSON Validator) is used to run the validation. Each test group
 * covers one resource type (Patient, Observation, DocumentReference).
 *
 * If Faker.js generates a wrong shape (e.g. an array instead of a string),
 * AJV will report the exact JSON path and expected type.
 */

// ajv-draft-04 supports the legacy `id` keyword (draft-04/06) used by the
// official FHIR R4 JSON Schema. AJV v8 (draft-07+) rejects `id` with an error.
import Ajv, { ErrorObject } from "ajv-draft-04";
import * as fs from "fs";
import * as path from "path";
import { db } from "../src/utils/dataGenerator";

// ---------------------------------------------------------------------------
// AJV Setup
// ---------------------------------------------------------------------------
// ajv-draft-04 natively supports draft-04/06 `id` keyword — no meta-schema needed.
// `validateSchema: false` skips AJV's self-validation of the FHIR schema
// (which declares "$schema": draft-06 — a version AJV would otherwise look up).
const ajv = new Ajv({ allErrors: true, strict: false, validateSchema: false });

// Load the full FHIR R4 JSON Schema (3.8 MB) once for all test suites.
const schemaPath = path.join(__dirname, "..", "schema", "fhir.schema.json");
const fhirSchema = JSON.parse(fs.readFileSync(schemaPath, "utf-8"));

// Add the entire schema (with all $defs/definitions) to AJV so that
// $ref resolution works correctly across the nested FHIR definitions.
ajv.addSchema(fhirSchema, "fhir");

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Builds a validate function for a specific FHIR definition (e.g. "Patient").
 * We resolve against the definitions block of the root schema.
 */
function getValidator(resourceType: string) {
  return ajv.compile({
    $ref: `fhir#/definitions/${resourceType}`,
  });
}

/** Returns a readable error string from AJV errors array. */
function formatErrors(errors: ErrorObject[] | null | undefined): string {
  if (!errors) return "no errors";
  return errors
    .map((e) => `  • [${e.instancePath || "/"}] ${e.message}  (schemaPath: ${e.schemaPath})`)
    .join("\n");
}

// ---------------------------------------------------------------------------
// Patient Tests
// ---------------------------------------------------------------------------
describe("Patient resources — FHIR schema validation", () => {
  const validate = getValidator("Patient");

  test("db contains at least 1 patient", () => {
    expect(db.patients.length).toBeGreaterThan(0);
  });

  test("every Patient passes FHIR schema validation", () => {
    for (const patient of db.patients) {
      const valid = validate(patient);
      if (!valid) {
        // Log detailed AJV errors before failing so the exact path is visible in output
        console.error(`Patient ${patient["id"]} failed:\n${formatErrors(validate.errors)}`);
      }
      expect(valid).toBe(true);
    }
  });

  test("every Patient has required FHIR fields (id, resourceType, name, gender, birthDate)", () => {
    for (const patient of db.patients) {
      expect(patient.id).toBeDefined();
      expect(patient.resourceType).toBe("Patient");
      // name must be an array of HumanName objects
      expect(Array.isArray(patient.name)).toBe(true);
      expect(patient.name.length).toBeGreaterThan(0);
      expect(typeof patient.name[0]?.family).toBe("string");
      expect(Array.isArray(patient.name[0]?.given)).toBe(true);
      // gender must be one of the FHIR allowed values
      expect(["male", "female", "other", "unknown"]).toContain(patient.gender);
      // birthDate must be a valid ISO date string (YYYY-MM-DD)
      expect(patient.birthDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    }
  });
});

// ---------------------------------------------------------------------------
// Observation Tests
// ---------------------------------------------------------------------------
describe("Observation resources — FHIR schema validation", () => {
  const validate = getValidator("Observation");

  test("db contains at least 1 observation", () => {
    expect(db.observations.length).toBeGreaterThan(0);
  });

  test("every Observation passes FHIR schema validation", () => {
    for (const obs of db.observations) {
      const valid = validate(obs);
      if (!valid) {
        console.error(`Observation ${obs["id"]} failed:\n${formatErrors(validate.errors)}`);
      }
      expect(valid).toBe(true);
    }
  });

  test("every Observation has required FHIR fields (subject, code, valueQuantity)", () => {
    for (const obs of db.observations) {
      expect(obs.resourceType).toBe("Observation");
      // subject.reference must be a string like "Patient/<uuid>"
      expect(typeof obs.subject.reference).toBe("string");
      expect(obs.subject.reference).toMatch(/^Patient\/.+/);
      // code must have a text label and at least one coding
      expect(typeof obs.code.text).toBe("string");
      expect(Array.isArray(obs.code.coding)).toBe(true);
      // valueQuantity must carry a numeric value and a unit string
      expect(typeof obs.valueQuantity.value).toBe("number");
      expect(typeof obs.valueQuantity.unit).toBe("string");
      // effectiveDateTime must be a valid ISO datetime string
      expect(new Date(obs.effectiveDateTime).toString()).not.toBe("Invalid Date");
    }
  });

  test("every Observation subject references a real Patient in the db", () => {
    const patientIds = new Set(db.patients.map((p) => p.id));
    for (const obs of db.observations) {
      const refId = obs.subject.reference.replace("Patient/", "");
      expect(patientIds.has(refId)).toBe(true);
    }
  });
});

// ---------------------------------------------------------------------------
// DocumentReference Tests
// ---------------------------------------------------------------------------
describe("DocumentReference resources — FHIR schema validation", () => {
  const validate = getValidator("DocumentReference");

  test("db contains at least 1 document", () => {
    expect(db.documentReferences.length).toBeGreaterThan(0);
  });

  test("every DocumentReference passes FHIR schema validation", () => {
    for (const doc of db.documentReferences) {
      const valid = validate(doc);
      if (!valid) {
        console.error(`DocumentReference ${doc["id"]} failed:\n${formatErrors(validate.errors)}`);
      }
      expect(valid).toBe(true);
    }
  });

  test("every DocumentReference has required FHIR fields (subject, date, content, type)", () => {
    for (const doc of db.documentReferences) {
      expect(doc.resourceType).toBe("DocumentReference");
      // subject.reference must point to a Patient
      expect(typeof doc.subject.reference).toBe("string");
      expect(doc.subject.reference).toMatch(/^Patient\/.+/);
      // date must be a valid ISO datetime
      expect(new Date(doc.date).toString()).not.toBe("Invalid Date");
      // content is a FHIR array of DocumentReference_Content items
      expect(Array.isArray(doc.content)).toBe(true);
      expect(doc.content.length).toBeGreaterThan(0);
      // each content item must carry an attachment with a base64-encoded narrative
      const attachment = doc.content[0]?.attachment;
      expect(attachment).toBeDefined();
      expect(typeof attachment?.data).toBe("string");
      expect(attachment?.data.length).toBeGreaterThan(0);
      expect(typeof attachment?.contentType).toBe("string");
      // type is a CodeableConcept (object), not a plain string
      expect(typeof doc.type).toBe("object");
      expect(typeof doc.type.text).toBe("string");
    }
  });

  test("every DocumentReference subject references a real Patient in the db", () => {
    const patientIds = new Set(db.patients.map((p) => p.id));
    for (const doc of db.documentReferences) {
      const refId = doc.subject.reference.replace("Patient/", "");
      expect(patientIds.has(refId)).toBe(true);
    }
  });
});
